const backCodes = {
    ACCESS_DENIED:  'ACCESS_DENIED',
    DUPLICATE_VAULT:  'DUPLICATE_VAULT',
    VAULT_NOT_FOUND: 'VAULT_NOT_FOUND',
    VAULT_SHARING_NOT_FOUND: 'VAULT_SHARING_NOT_FOUND',

    RECIPIENT_NOT_FOUND:  'RECIPIENT_NOT_FOUND',
    RECIPIENT_ALREADY:  'RECIPIENT_ALREADY',
    
    DUPLICATE_CREDENTIAL:  'DUPLICATE_CREDENTIAL',
    CREDENTIAL_ACCESS_DENIED: 'CREDENTIAL_ACCESS_DENIED',
};

export default backCodes;